language:
  code: de
  name: Wikipedia
  local_name: Deutsch
  iso_code: de-DE
wikipedia:
  dbname: dewiki
  redirect_keywords:
  - '#WEITERLEITUNG'
  - '#REDIRECT'
  disambiguation_markers:
  - '{{Begriffskl√§rung}}'
  - '{{disambig}}'
  stub_markers:
  - '{{Stub}}'
  - '{{kurz}}'
  namespace_prefixes:
    file: &id001
    - 'File:'
    - 'Datei:'
    - 'Bild:'
    - 'Image:'
    template:
    - 'Template:'
    - 'Vorlage:'
    category:
    - 'Category:'
    - 'Kategorie:'
text_processing:
  encoding: utf-8
  has_spaces: true
  word_separator: ' '
  stemmer: snowball
infobox:
  template_prefixes:
  - Infobox
text_cleanup:
  file_patterns: *id001
