language:
  code: pl
  name: Wikipedia
  local_name: Polski
  iso_code: pl-PL
wikipedia:
  dbname: plwiki
  redirect_keywords:
  - '#PATRZ'
  - '#PRZEKIERUJ'
  - '#TAM'
  - '#REDIRECT'
  disambiguation_markers:
  - '{{disambig}}'
  - '{{ujednoznacznienie}}'
  stub_markers:
  - '{{stub}}'
  - '{{zalążek}}'
  namespace_prefixes:
    file: &id001
    - 'File:'
    - 'Plik:'
    - 'Grafika:'
    - 'Image:'
    template:
    - 'Template:'
    - 'Szablon:'
    category:
    - 'Category:'
    - 'Kategoria:'
text_processing:
  encoding: utf-8
  has_spaces: true
  word_separator: ' '
  stopwords_path: config/stopwords/pl.txt
  stemmer: snowball
infobox:
  template_prefixes:
  - Infobox
  - Infokarta
  parameter_map:
    urodzony: born
    zmarł: died
    lokalizacja: location
    powierzchnia: area
    populacja: population
ui:
  search_placeholder: Szukaj w polskiej Wikipedii...
  language_name: Polski
  interface_translations:
    show_connections: Pokaż połączenia
    related_articles: Powiązane artykuły
    categories: Kategorie
text_cleanup:
  file_patterns: *id001
